import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Search, ShoppingBag } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cyber Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav className="w-full flex items-center justify-between px-4 py-2 border-b border-gray-300 mb-4">
            <div className="flex items-center gap-6">
              <h1><Link href={'/'}>Cyberhub</Link></h1>
              <ul className="flex items-center gap-4">
                <li><Link href={'/stories'}>Stories</Link></li>
                <li><Link href={'/forum'}>Forum</Link></li>
                <li><Link href={'/store'}>Store</Link></li>
                <li><Link href={'/contact'}>Contact</Link></li>
              </ul>
            </div>
            <ul className="flex items-center gap-4">
              <li><Search /></li>
              <li><ShoppingBag /></li>
            </ul>
          </nav>
        </header>
        <main className="w-[97vw] max-w-[1300px] mx-auto overflow-hidden ">{children}</main>
      </body>
    </html>
  );
}
